"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.reviewRoutes = void 0;
const enums_1 = require("@prisma/enums");
const checkAuth_1 = require("app/middlewares/checkAuth");
const validationRequest_1 = require("app/middlewares/validationRequest");
const express_1 = require("express");
const review_controller_1 = __importDefault(require("./review.controller"));
const review_validation_1 = require("./review.validation");
// import { CheckAuth } from "src/app/middlewares/checkAuth";
// import { validationRequest } from "src/app/middlewares/validationRequest";
const router = (0, express_1.Router)();
router.get('/my-reviews', (0, checkAuth_1.CheckAuth)(enums_1.Role.USER, enums_1.Role.ADMIN), review_controller_1.default.getMyReviews);
router.get('/user/:userId', review_controller_1.default.getUserReviews);
router.post('/', (0, checkAuth_1.CheckAuth)(enums_1.Role.USER, enums_1.Role.ADMIN), (0, validationRequest_1.validationRequest)(review_validation_1.createReviewValidation), review_controller_1.default.createReview);
router.patch('/:id', (0, checkAuth_1.CheckAuth)(enums_1.Role.USER, enums_1.Role.ADMIN), (0, validationRequest_1.validationRequest)(review_validation_1.updateReviewValidation), review_controller_1.default.updateReview);
router.delete('/:id', (0, checkAuth_1.CheckAuth)(enums_1.Role.USER, enums_1.Role.ADMIN), review_controller_1.default.deleteReview);
exports.reviewRoutes = router;
